### ISSUE TITLE
服务器地址是填本机的IP地址吗，我填127.0.0.1：5000报错了

### ISSUE THREAD

**Issue by tz95827** [2020sjkks/2020sjkks#5]
[
![截图](https://user-images.githubusercontent.com/59287467/111864401-9a80ca80-899b-11eb-8491-8561d0730773.png)
](url)

非常谢谢您的分享

**Comment by hongwei7** [comment]
是否有启动flask后端服务呢？如果有的话，检查一下后端那边log的内容

**Comment by hongwei7** [comment]
猜测是pymysql的版本升级导致。参考https://blog.csdn.net/SunshinePluto/article/details/112555362
